AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3.3

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 60
Metrics/BlockLength:
  Max: 30
Metrics/MethodLength:
  Max: 40
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/ParameterLists:
  Max: 10
Layout/AlignParameters:
  Enabled: false
